### ISSUE TITLE
Block Treemap - text updates to section titles 

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/q1_report#13]
@kuanb some of the text is missing spaces and other text could use more description to be clear. Below are some ideas. - Also, Is length of text an issue? 

Competingsupervisionreqs = Competing supervision requirements
Overscheduled = Over scheduled 
Hasconflict = Has conflict 
Quietcompletion = Quiet completion of supervision
CJS Relationship = Criminal Justice Services 
Status = Life status 
Socialties = Social Ties
In Foster Care = Has child in Foster Care
DCFS = Has a second case manager with DCFS
Personal = Health and Personal Issues 
Family = Reunite with Family

**Comment by kuanb** [comment]
what does Life status mean?

**Comment by kuanb** [comment]
good as of 1f6255f

**Comment by bpdesigns** [comment]
@kuanb I was trying to make "Status" more descriptive, but looking at the interactive viz, I think "Life status" is may be more unclear. I think "Status" was a probably better descriptor. I recommend we go back to that word. Sorry for the back and forth on that.

**Comment by kuanb** [comment]
No prob will switch back
