### ISSUE TITLE
Collapsable tree diagram - text is cut off on the right as you drill down into the page

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/q1_report#14]
![screen shot 2016-04-22 at 9 51 40 am](https://cloud.githubusercontent.com/assets/15329140/14748686/f60c70f0-086f-11e6-9da1-4ed52b5abf1b.png)

**Comment by bpdesigns** [comment]
Idea 1: Add a scroll bar for top section of viz.
Idea 2: Force frame to the width of data viz when all text is open. (not a great idea, but an option)

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/14925734/b3e036ba-0dfd-11e6-89f5-2e75fe6365de.png)

scroll in action

**Comment by kuanb** [comment]
resolved via 60c1bdd..1aecf45
