### ISSUE TITLE
Collapsable Tree Diagram - last branch showing goals is unclear. Two suggestions 

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/q1_report#19]
I think it isn't clear what they are. We don't provide any context for them. Having descriptors and then quotes is a clear progression, but we don't state anywhere the next text is their goals 

1) remove the last branch with "goals' completely. 

2) or - put the text "Archetype Goals: " before showing what the goals are.

**Comment by kuanb** [comment]
Think 2nd idea is way to go

**Comment by bpdesigns** [comment]
Sure.

**Comment by kuanb** [comment]
6fcae80 resolves

**Comment by bpdesigns** [comment]
@kuanb awesome! Can the scroll bar be visible always? Visually it was unclear to me that there was a scroll bar before trying to find it by moving on the page.

**Comment by kuanb** [comment]
So we introduced the auto scroll right which resolved this issue somewhat... hidden scroll bar is an issue with mac os x....

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/15050065/7828e61e-12a6-11e6-9635-4e9385b8fe84.png)

potential style of forced scroll
