### ISSUE TITLE
Block Treemap - Alternatives to sorting by archetype 

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/q1_report#2]
Sort by:
- Age range
- Communication preferences
- First or Multiple times through

**Comment by bpdesigns** [comment]
@kuanb what do you think? I'm wondering if makes more sense to amke

**Comment by bpdesigns** [comment]
@kuanb some ideas. I was thinking if the tree map is specifically about archetypes, maybe we can use this graphic to dig into the content in a different way. One of the things we might find is there might be a correlation between how many times through the system and comms preferences or what support a person has.

**Comment by kuanb** [comment]
I think maybe I need to build that stat view version of the data viz

**Comment by bpdesigns** [comment]
@kuanb can you elaborate?

**Comment by kuanb** [comment]
Yeah. Breaking those variants down by those different components is perhaps a tad confusing in the boxes diagram because those variables are held <i>within</i> the boxes as a variable... so you would effectively create 100% or null instances by selecting them as a sort attribute

i am making a bar chart that resizes depending on drill downs now that allows for the querying you described at the top

**Comment by kuanb** [comment]
i think it will also help with generating the missing graphs, etc

**Comment by bpdesigns** [comment]
Sounds good. Thanks Kuan

On Fri, Apr 22, 2016 at 9:51 AM, Kuan Butts notifications@github.com
wrote:

> i think it will also help with generating the missing graphs, etc
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/slco-2016/q1_report/issues/2#issuecomment-213508465

## 

_Volunteer your skills._ \*  Find your local Code for America Brigade.
http://www.codeforamerica.org/brigade/?source_codes=staff *

Ben Peterson // Designer, 2016 _Code for America Fellow
http://www.codeforamerica.org/geeks/fellowship-apply/?source_codes=staff *
// (385) 202-5458 // *@bpdesign https://twitter.com/bpdesign_

**Comment by kuanb** [comment]
added the new data viz screen, comments on layout will be on new issues
