### ISSUE TITLE
Collapsable tree diagram - extra word in quote

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/q1_report#21]
![screen shot 2016-04-25 at 8 42 40 am](https://cloud.githubusercontent.com/assets/15329140/14789513/c76fe3e0-0ac1-11e6-9391-177beb9c70a1.png)
See lower right hand of image. Delete second "the" to make the quote read “[This is the] first time in a long time I'm doing good. I’m proud of myself.”

**Comment by bpdesigns** [comment]
@kuanb Note for the Full Report. This also occurs on the long form report under "Achievement Focused (see: http://slco-2016.github.io/q1_report_long/researchoutcomes_page/ ), but is fine in short form report.

**Comment by kuanb** [comment]
af01770 resolves
