### ISSUE TITLE
report - archetype and insight pages. Change link state on hover

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/q1_report#25]
Change link state to blue circle (see below) on hover for archetype and insight pages.
![rollover-archetypes-button](https://cloud.githubusercontent.com/assets/15329140/14905029/e4e6daee-0d61-11e6-9612-d3f34a262ff4.png)

**Comment by kuanb** [comment]
cha ching 
![image](https://cloud.githubusercontent.com/assets/6053396/14905828/a9333f08-0d69-11e6-83a0-4d574b0dffe5.png)

**Comment by kuanb** [comment]
resolved via 0b2b7c9
