### ISSUE TITLE
Attribute Distributions - text on x axis overlaps on certain pages

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/q1_report#28]
Idea: Place x-axis text on a 45% angle.

![screen shot 2016-04-28 at 5 05 34 pm](https://cloud.githubusercontent.com/assets/15329140/14905210/73302cd2-0d63-11e6-8070-7319fce547e8.png)

**Comment by kuanb** [comment]
I think the angle is aggressive because then we need to size the bottom height...
Gonna try putting them on top of the bars first? Might be easier. Then bleed overs wont over lap since bars are different heights

LMK if that idea is undesirable

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/14905798/58cb8d0e-0d69-11e6-91a7-32867d543051.png)

think it looks pretty decent

**Comment by kuanb** [comment]
resolved via cee4687

**Comment by bpdesigns** [comment]
@kuanb Looks good!
