### ISSUE TITLE
Attribute Distributions - text edits

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/q1_report#29]
"Girlboyfriend" = "Significant Other" or "Girl/Boyfriend"
"Marriage" = "Relationship" or "Relationship Status"
"Child Support" = "Has Child Support" or "Owes Child Support"
"Positive" = "Positive Social Ties" or "Positive Ties"
"Negative" = "Negative Social Ties" or "Negative Ties"

**Comment by kuanb** [comment]
marriage should be that specifically, not just relationship... perhaps "Married"?

**Comment by kuanb** [comment]
resolved via https://github.com/slco-2016/q1_report/commit/a67a3b6ab1eefac6745c4e6743ca4b64c772ff9c

**Comment by bpdesigns** [comment]
Needsreminders = "Needs reminders"

**Comment by bpdesigns** [comment]
Re: Married. I think it works. Doesn't fit exactly but best we can do I think.

**Comment by kuanb** [comment]
a67a3b6..60c1bdd resolves
