### ISSUE TITLE
Archetypes Tree Diagram - Category boxes no longer fill with text

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/q1_report#32]

**Comment by kuanb** [comment]
in modBaseText:

`if (source.depth == 1) { 
        $("#title-category").text(source.name); 
        $("#title-subcat").text("Sub-category"); 
        $("#category").html(source.quotes.join("<br>")); 
        $("#subcat").text("");
      } else if (source.depth == 2) {
        $("#title-category").text(source.parent.name); 
        $("#title-subcat").text(source.name); 
        $("#category").html(source.parent.quotes.join("<br>")); 
        $("#subcat").html("<i>\"" + source.quotes.join("\"</i><br><i>\"") + "\"</i>"); 
      }`
