### ISSUE TITLE
Archetypes Tree Diagram - Description update for context

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/q1_report#33]
@kuanb In the same we labeled Goals on the last branch of the tree. I think it would be helpful to add descriptions to two other branches.

ex: Consequence Focused / Main Traits: Younger with family support and negative social circles / Interview Quote: I just got to stop hanging out with certain other people.

If you have a better way of describing "Main Traits" that would be great.

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/15050413/82451846-12a8-11e6-8e04-568895a45e1f.png)

done

**Comment by kuanb** [comment]
i think just "Trait" is more succinct
