### ISSUE TITLE
Text Readability - Globally change Source Sans Black to Source Sans Bold

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/q1_report#4]

**Comment by kuanb** [comment]
Can we get more specificity? We want everything in bold?

**Comment by kuanb** [comment]
There are weights - I think small text at full weight (900) would be aggressive

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/14623156/1eab1fc6-0595-11e6-9582-1033aec29d2c.png)
 I used 700 in the index. I think that's ok and improved legibility

**Comment by bpdesigns** [comment]
This looks great. ...I think there was a misunderstanding. I meant by that comment to change all text that's currently 900 (Black) to 700 (Bold).
