### ISSUE TITLE
Block Treemap - Layout edit

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/q1_report#6]
Here are some layout ideas to make the navigation clearer. 
1. top row: title and back button on the 
2. second row: archetypes and navigation breadcrumbs
3. Text size change: navigation breadcrumbs = to the Archetypes menu box

![treeblocks](https://cloud.githubusercontent.com/assets/15329140/14616714/61018444-0560-11e6-9477-7c116b35b621.jpg)

**Comment by kuanb** [comment]
resolved via https://github.com/slco-2016/q1_report/commit/ec4071bae1bb45e433b5e11e7b2cc11678c003a9

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/14618081/7e507aee-0576-11e6-8425-842d3fe25b9f.png)

**Comment by kuanb** [comment]
Correction this one resolves: https://github.com/slco-2016/q1_report/commit/df4651a08603240c02f93d2f01b9685ca49e06e1
