### ISSUE TITLE
Index Layout Design edit

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/q1_report#7]
BG color: Dark Blue, #004b6a, $color-dark-blue
Text/ Primary color: Light Blue, #7ab5d6, $color-light-blue
Fonts: Source Sans Pro, Source Sans Pro Bold
On enter: I would fade the large box buttons out slower, maybe 3 seconds?
Box Button Size: 1/4 size larger

![indexdesignedits-03](https://cloud.githubusercontent.com/assets/15329140/14617020/6f43d47a-0561-11e6-85c6-b98e5a96ab90.jpg)
![indexdesignedits-04](https://cloud.githubusercontent.com/assets/15329140/14617078/bfe93460-0561-11e6-864c-4c6baa3efe18.jpg)

**Comment by kuanb** [comment]
This is cool - do we want to go with this specific layout for sure? I remember there being some concerns about layout being confusing esp for non-technical folks.

**Comment by kuanb** [comment]
Like the colors, though

**Comment by bpdesigns** [comment]
To address potential confusion with navigation (1) I've added two more sketches below. (2) When the user enters the site having the buttons animate to show that they are interactive might help.

![indexdesignedits-08](https://cloud.githubusercontent.com/assets/15329140/14619942/f498de92-056e-11e6-8de8-7aafcaf4b6cf.jpg)
![indexdesignedits-07](https://cloud.githubusercontent.com/assets/15329140/14619945/f6965bf2-056e-11e6-9e70-d55162c0af23.jpg)

**Comment by kuanb** [comment]
colors for new design?
what color is that light blue?

**Comment by kuanb** [comment]
Light blue: #4BAEFF
Dark blue: #033F7B

**Comment by kuanb** [comment]
Do the circles indicate icons?

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/14622442/91434956-058f-11e6-9215-3d59ce9ffd59.png)

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/14623035/20a1bd9a-0594-11e6-8d2e-a4cc7814bcbf.png)

we have sliding now

**Comment by kuanb** [comment]
I think we need to also discuss what does where (what each title is)

In the meantime I think the style has been implemented... So I will close this issue

**Comment by kuanb** [comment]
resolved via https://github.com/slco-2016/q1_report/commit/218f003707c6f7b455f2e10b8f416994d0950a43
