### ISSUE TITLE
Data Viz pages - color suggestions

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/q1_report#8]
BG: Black
Buttons: Light Blue, #7ab5d6, $color-light-blue
Primary Text: White or Light Blue

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/14618600/05edd6f2-0579-11e6-9f2c-140f2f69b2e4.png)

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/14618648/42f6a506-0579-11e6-82a2-ec9eb9d2b3b6.png)

**Comment by kuanb** [comment]
https://github.com/slco-2016/q1_report/commit/b359577f9c6f27846eed1adee004f0310c140dd9 resovled
